# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QuickShapeUpdate
                                 A QGIS plugin
 This plugin updates the shapes length and/or area in the selected layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-11-01
        copyright            : (C) 2023 by Sylvain Milliot
        email                : milliot.sylvain@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QuickShapeUpdate class from file QuickShapeUpdate.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .quick_shape_update import QuickShapeUpdate
    return QuickShapeUpdate(iface)
